# Generated by Django 4.2.10 on 2025-08-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_passport_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="faceauthenticationlog",
            new_name="users_facea_user_id_b2228e_idx",
            old_name="users_faceauth_user_time_idx",
        ),
        migrations.RenameIndex(
            model_name="faceauthenticationlog",
            new_name="users_facea_status_115b87_idx",
            old_name="users_faceauth_status_time_idx",
        ),
        migrations.RenameIndex(
            model_name="passportdata",
            new_name="users_passp_pinfl_54a191_idx",
            old_name="users_passpo_pinfl_idx",
        ),
        migrations.RenameIndex(
            model_name="passportdata",
            new_name="users_passp_passpor_72f289_idx",
            old_name="users_passpo_series_num_idx",
        ),
    ]
