# Generated by Django 4.2.10 on 2025-08-17 19:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0004_rename_users_faceauth_user_time_idx_users_facea_user_id_b2228e_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ps_ser",
                    models.CharField(max_length=3, verbose_name="Passport seriyasi"),
                ),
                (
                    "ps_num",
                    models.CharField(max_length=10, verbose_name="Passport raqami"),
                ),
                (
                    "pnfl",
                    models.BigIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="PNFL 14 ta raqamdan iborat bo'lishi kerak.",
                                regex="^[0-9]{14}$",
                            )
                        ],
                        verbose_name="PINFL/JSHSHIR",
                    ),
                ),
                ("sname", models.CharField(max_length=63, verbose_name="Familiya")),
                ("fname", models.CharField(max_length=63, verbose_name="Ism")),
                (
                    "mname",
                    models.CharField(max_length=63, verbose_name="Otasining ismi"),
                ),
                (
                    "birth_place",
                    models.CharField(max_length=127, verbose_name="Tug'ilgan joy"),
                ),
                ("birth_date", models.DateField(verbose_name="Tug'ilgan sana")),
                (
                    "birth_country",
                    models.CharField(max_length=127, verbose_name="Tug'ilgan davlat"),
                ),
                (
                    "birth_country_id",
                    models.IntegerField(verbose_name="Tug'ilgan davlat ID"),
                ),
                (
                    "livestatus",
                    models.CharField(
                        choices=[("0", "Tirik"), ("1", "Vafot etgan")],
                        default="0",
                        max_length=1,
                        verbose_name="Hayot holati",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(max_length=127, verbose_name="Millati"),
                ),
                ("nationality_id", models.IntegerField(verbose_name="Millat ID")),
                (
                    "sex",
                    models.CharField(
                        choices=[("1", "Erkak"), ("2", "Ayol")],
                        max_length=1,
                        verbose_name="Jinsi",
                    ),
                ),
                (
                    "doc_give_place",
                    models.CharField(
                        max_length=255, verbose_name="Passport berilgan joy"
                    ),
                ),
                (
                    "doc_give_place_id",
                    models.IntegerField(verbose_name="Passport berilgan joy ID"),
                ),
                (
                    "matches_date_begin_document",
                    models.DateField(verbose_name="Passport berilgan sana"),
                ),
                (
                    "matches_date_end_document",
                    models.DateField(verbose_name="Passport amal qilish muddati"),
                ),
                (
                    "photo",
                    models.TextField(
                        help_text="Government API'dan olingan rasm",
                        verbose_name="Passport rasmi (Base64)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Tasdiqlangan"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tasdiqlangan vaqt"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="full_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi profili",
                "verbose_name_plural": "Foydalanuvchi profillari",
                "indexes": [
                    models.Index(fields=["pnfl"], name="users_userp_pnfl_6d1c4c_idx"),
                    models.Index(
                        fields=["ps_ser", "ps_num"],
                        name="users_userp_ps_ser_540a20_idx",
                    ),
                ],
            },
        ),
    ]
