# Generated by Django 4.2.10 on 2025-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passport",
            field=models.CharField(
                blank=True,
                help_text="Passport series and number (e.g., AC1987867)",
                max_length=10,
                null=True,
                verbose_name="Passport Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pnfl",
            field=models.CharField(
                blank=True,
                help_text="14-digit personal identification number",
                max_length=14,
                null=True,
                unique=True,
                verbose_name="PINFL/JSHSHIR",
            ),
        ),
    ]
