# Generated by Django 4.2.10 on 2025-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_passport_user_pnfl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Administrator"),
                    ("ADMIN", "Administrator"),
                    ("QB_EXPERT", "Question Bank Expert"),
                    ("Q_EXPERT", "Question Expert"),
                    ("CREATOR", "Question Creator"),
                ],
                default="CREATOR",
                max_length=15,
                verbose_name="User Role",
            ),
        ),
    ]
