# Generated by Django 4.2.10 on 2025-08-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_remove_old_fields"),
        ("users", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expert_fan",
            field=models.ForeignKey(
                blank=True,
                help_text="Fan which this Q_EXPERT specializes in (only for Q_EXPERT role)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expert_users",
                to="questions.fan",
                verbose_name="Expert Fan",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Administrator"),
                    ("ADMIN", "Book Expert"),
                    ("QB_EXPERT", "Question Bank Expert"),
                    ("Q_EXPERT", "Question Expert"),
                    ("CREATOR", "Q Creator"),
                ],
                default="CREATOR",
                max_length=15,
                verbose_name="User Role",
            ),
        ),
    ]
