# Generated by Django 4.2.10 on 2025-08-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_section_subject_topic_and_more"),
        ("users", "0008_add_expert_fan_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="expert_fan",
        ),
        migrations.AddField(
            model_name="user",
            name="expert_subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject which this Q_EXPERT specializes in (only for Q_EXPERT role)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expert_users",
                to="questions.subject",
                verbose_name="Expert Subject",
            ),
        ),
    ]
