# Generated by Django 4.2.10 on 2025-08-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_banks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankquestion",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_questions",
                to="question_banks.questionbank",
                verbose_name="Bank",
            ),
        ),
    ]
