# Generated by Django 4.2.10 on 2025-08-18 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_remove_old_fields"),
        ("question_banks", "0002_alter_bankquestion_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPointDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questions_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Savollar soni",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("EASY", "Oson"),
                            ("MEDIUM", "O'rta"),
                            ("HARD", "Qiyin"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Qiyinlik darajasi",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_distributions",
                        to="question_banks.bankorder",
                        verbose_name="Buyurtma",
                    ),
                ),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.paragraph",
                        verbose_name="Bo'lim",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.point",
                        verbose_name="Mavzu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punkt bo'yicha taqsimot",
                "verbose_name_plural": "Punktlar bo'yicha taqsimot",
                "unique_together": {("order", "point", "difficulty_level")},
            },
        ),
    ]
