# Generated by Django 4.2.10 on 2025-08-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question_banks", "0003_orderpointdistribution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderpointdistribution",
            options={
                "verbose_name": "Topic distribution",
                "verbose_name_plural": "Topic distributions",
            },
        ),
    ]
