# Generated by Django 4.2.10 on 2025-08-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_banks", "0004_alter_orderpointdistribution_options"),
        ("questions", "0006_section_subject_topic_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderpointdistribution",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="questionbank",
            name="fan",
        ),
        migrations.AddField(
            model_name="orderpointdistribution",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.section",
                verbose_name="Section",
            ),
        ),
        migrations.AddField(
            model_name="orderpointdistribution",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.topic",
                verbose_name="Topic",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_banks",
                to="questions.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderpointdistribution",
            unique_together={("order", "topic", "section", "difficulty_level")},
        ),
        migrations.RemoveField(
            model_name="orderpointdistribution",
            name="paragraph",
        ),
        migrations.RemoveField(
            model_name="orderpointdistribution",
            name="point",
        ),
    ]
