# Generated by Django 4.2.10 on 2025-08-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_add_difficulty_model"),
        (
            "question_banks",
            "0005_alter_orderpointdistribution_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTopicQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kerakli savollar soni"
                    ),
                ),
                (
                    "current_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Hozirgi savollar soni"
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_quotas",
                        to="question_banks.questionbank",
                        verbose_name="Savol to'plami",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.difficulty",
                        verbose_name="Qiyinlik darajasi",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.section",
                        verbose_name="Bo'lim",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.topic",
                        verbose_name="Mavzu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mavzu kvotasi",
                "verbose_name_plural": "Mavzu kvotalari",
                "ordering": ["topic__number", "difficulty__level"],
                "unique_together": {("bank", "topic", "section", "difficulty")},
            },
        ),
    ]
