# Generated by Django 4.2.10 on 2025-08-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_add_difficulty_model"),
        ("question_banks", "0006_add_topic_quotas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionbank",
            name="expert",
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_banks",
                to="questions.subject",
                verbose_name="Fan",
            ),
        ),
    ]
