# Generated by Django 4.2.10 on 2025-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_remove_old_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Section Name")),
                ("number", models.PositiveIntegerField(verbose_name="Section Number")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["topic__subject__name", "topic__number", "number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Subject Name")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Subject Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Topic Name")),
                ("number", models.PositiveIntegerField(verbose_name="Topic Number")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["subject__name", "number"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="paragraph",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="paragraph",
            name="fan",
        ),
        migrations.AlterUniqueTogether(
            name="point",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="point",
            name="paragraph",
        ),
        migrations.RemoveField(
            model_name="question",
            name="fan",
        ),
        migrations.RemoveField(
            model_name="question",
            name="paragraph",
        ),
        migrations.RemoveField(
            model_name="question",
            name="point",
        ),
    ]
