# Generated by Django 4.2.10 on 2025-08-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "question_banks",
            "0005_alter_orderpointdistribution_unique_together_and_more",
        ),
        ("questions", "0006_section_subject_topic_and_more"),
        ("users", "0009_remove_user_expert_fan_user_expert_subject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fan",
        ),
        migrations.DeleteModel(
            name="Paragraph",
        ),
        migrations.DeleteModel(
            name="Point",
        ),
        migrations.AddField(
            model_name="topic",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="questions.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="questions.topic",
                verbose_name="Topic",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.section",
                verbose_name="Section",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.topic",
                verbose_name="Topic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("subject", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("topic", "number")},
        ),
    ]
