# Generated by Django 4.2.10 on 2025-08-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_delete_fan_delete_paragraph_delete_point_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Difficulty Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Difficulty Code"
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Lower number = easier",
                        unique=True,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Difficulty",
                "verbose_name_plural": "Difficulties",
                "ordering": ["level"],
            },
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("EASY", "Easy"), ("MEDIUM", "Medium"), ("HARD", "Hard")],
                default="MEDIUM",
                help_text="DEPRECATED - Use difficulty_level instead",
                max_length=10,
                verbose_name="Difficulty Level (OLD)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="questions.difficulty",
                verbose_name="Difficulty Level",
            ),
        ),
    ]
