# Generated by Django 4.2.10 on 2025-09-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0008_add_difficulty_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="parent_question",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent question for reading comprehension sub-questions",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_questions",
                to="questions.question",
                verbose_name="Parent Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_order",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Order of sub-questions in reading comprehension",
                verbose_name="Question Order",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single Choice"),
                    ("MULTIPLE", "Multiple Choice"),
                    ("READING", "Reading Comprehension"),
                ],
                default="SINGLE",
                max_length=10,
                verbose_name="Question Type",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="reading_text",
            field=models.TextField(
                blank=True,
                help_text="Main reading text for comprehension questions",
                verbose_name="Reading Text",
            ),
        ),
    ]
