# Generated by Django 4.2.10 on 2025-09-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0009_question_parent_question_question_question_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted for Review"),
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
